image: ubuntu:latest

stages:
  - build
  - package
  - test
  - deploy

services:
  - docker:dind
  - docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASSWORD

before_script:
  - add-apt-repository ppa:webupd8team/java
  - add-apt-repository ppa:openjdk-r/ppa
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
  - apt-get update
  - echo \
    "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu \
    $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
  - wget https://downloads.apache.org/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.tar.gz -P /tmp
  - apt-get update
  - apt-get install openjdk-8-jdk -y
  - apt-get -y install maven
  - apt-get install docker-ce docker-ce-cli containerd.io -y


maven-build:
  stage: build
  script: "mvn clean package"




docker-build:
  services:
    - docker:dind
    - docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASSWORD
  before_script:
    - docker info
  stage: package
  script:
    - docker build -t dock-product-api .
    - docker tag dock-test caiocaminha/dock-product-api:latest
    - docker push caiocaminha/dock-product-api:latest