image: docker:stable

stages:
  - build
  - package
  - test
  - deploy

services:
  - docker:dind
  - docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASSWORD


application-deploy:
  image: ubuntu:latest
  stage: deploy
  script:
    - apt-get update
    - chmod 400 dock-product-api.pem
    - apt-get install openssh-server -y
    - service ssh start
    - ssh-keyscan ec2-54-224-232-53.compute-1.amazonaws.com
    - ssh-keygen -f "/home/ubuntu/.ssh/known_hosts" -R
    - ssh -i "dock-product-api.pem" ubuntu@ec2-54-224-232-53.compute-1.amazonaws.com
    - sudo su
    - docker pull caminhacaio/dock-product-api:latest
    - docker rm $(docker ps -a -q)
    - docker run -d -p 8085:8085 caminhacaio/dock-product-api