image: docker:stable

stages:
  - build
  - package
  - test
  - deploy

services:
  - docker:dind
  - docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASSWORD

before_script:
  - docker info


maven-build:
  services:
    - maven:3-jdk-17
  stage: build
  script: "mvn clean package"




docker-build:
  services:
    - docker:dind
    - docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASSWORD
  before_script:
    - docker info
  stage: package
  script:
    - docker build -t dock-product-api .
    - docker tag dock-test caiocaminha/dock-product-api:latest
    - docker push caiocaminha/dock-product-api:latest