image: docker:stable

stages:
  - build
  - package
  - test
  - deploy

services:
  - docker:dind
  - docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASSWORD


application-deploy:
  image: ubuntu:latest
  stage: deploy
  before_script:
    - apk add openssh-client
    - eval $(ssh-agent -s)
    - echo "$DOCK_PRODUCT_API" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
  script:
    - apt-get update
    - apt-get install openssh-server -y
    - service ssh start
    - ssh -o StrictHostKeyChecking=no ubuntu@ec2-54-224-232-53.compute-1.amazonaws.com "docker pull caminhacaio/dock-product-api:latest; docker rm $(docker ps -a -q); docker run -d -p 8085:8085 caminhacaio/dock-product-api"
