image: docker:stable

stages:
  - build
  - package
  - test
  - deploy

services:
  - docker:dind
  - docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASSWORD




application-test:
  stage: test
  script:
    - mvn test
  dependencies:
    - docker-build